In [1]:
import pandas as pd
import json
from io import BytesIO

pd.set_option('display.max_columns', None)

In [2]:
#Read All events data
matchId = 1
player_list = pd.DataFrame()
events_all = pd.DataFrame()
for i in range(1,38):
    #Read json based on declared match
    read_json = open(f'mu_data/{i}.json', encoding="utf-8")
    
    #Load json data
    data = json.load(read_json)
    
    #Put json data on dataframe and normalize it
    events = pd.json_normalize(data['events'])
    
    #Add matchId data to differentiate between matches
    events['matchId']=matchId
    matchId = matchId + 1
    
    #append all events data into 1 dataframe
    events_all = events_all.append(events,ignore_index=True)
    
    #read player name and put into list
    player_name = pd.json_normalize(data['playerIdNameDictionary']).transpose()
    player_name = player_name.reset_index()
    player_name = player_name.rename(columns={"index":"playerId",0:"player_name"})
    player_name['playerId'] = player_name['playerId'].astype(int, errors = 'raise')   
    player_list = pd.concat([player_list,player_name]).drop_duplicates().reset_index(drop=True)
    
#get player name into events data   
events_all = events_all.merge(player_list,on='playerId',how='left')

In [3]:
events_all

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
0,2.443300e+09,2,0,0.0,211,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
1,2.443300e+09,2,0,0.0,32,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
2,2.443300e+09,3,0,0.0,211,50.0,50.0,0,"[{'type': {'value': 213, 'displayName': 'Angle...","[91, 117, 30, 35, 38, 215, 218]",True,1,FirstHalf,1,Pass,1,Successful,21683.0,30.7,46.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adam Lallana
3,2.443300e+09,4,0,3.0,211,31.6,43.4,0,"[{'type': {'value': 1, 'displayName': 'Longbal...","[91, 120, 124, 128, 36, 38, 217, 218]",True,1,FirstHalf,1,Pass,0,Unsuccessful,86441.0,78.3,26.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lewis Dunk
4,2.443300e+09,3,0,6.0,32,20.8,78.7,0,[],[93],False,1,FirstHalf,49,BallRecovery,1,Successful,340105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lisandro Mart√≠nez
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56945,2.508426e+09,892,94,30.0,65,0.0,0.0,97,[],[],False,2,SecondHalf,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56946,2.508426e+09,893,0,0.0,65,0.0,0.0,7,[],[],False,14,PostGame,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56947,2.508427e+09,720,0,0.0,32,0.0,0.0,7,[],[],False,14,PostGame,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56948,2.508378e+09,1,0,0.0,65,0.0,0.0,0,"[{'type': {'value': 194, 'displayName': 'Capta...",[],False,16,PreMatch,34,FormationSet,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56949,2.508378e+09,1,0,0.0,32,0.0,0.0,0,"[{'type': {'value': 194, 'displayName': 'Capta...",[],False,16,PreMatch,34,FormationSet,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN

In [4]:
events_all.to_csv('mu_events_2022_2023.csv')

In [63]:
events_all = pd.read_csv('mu_events_2022_2023.csv',index_col=0)

# Corner

In [64]:
corner_data = events_all

In [65]:
corner_data

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
0,2.443300e+09,2,0,0.0,211,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
1,2.443300e+09,2,0,0.0,32,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
2,2.443300e+09,3,0,0.0,211,50.0,50.0,0,"[{'type': {'value': 213, 'displayName': 'Angle...","[91, 117, 30, 35, 38, 215, 218]",True,1,FirstHalf,1,Pass,1,Successful,21683.0,30.7,46.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adam Lallana
3,2.443300e+09,4,0,3.0,211,31.6,43.4,0,"[{'type': {'value': 1, 'displayName': 'Longbal...","[91, 120, 124, 128, 36, 38, 217, 218]",True,1,FirstHalf,1,Pass,0,Unsuccessful,86441.0,78.3,26.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lewis Dunk
4,2.443300e+09,3,0,6.0,32,20.8,78.7,0,[],[93],False,1,FirstHalf,49,BallRecovery,1,Successful,340105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lisandro Mart√≠nez
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56945,2.508426e+09,892,94,30.0,65,0.0,0.0,97,[],[],False,2,SecondHalf,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56946,2.508426e+09,893,0,0.0,65,0.0,0.0,7,[],[],False,14,PostGame,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56947,2.508427e+09,720,0,0.0,32,0.0,0.0,7,[],[],False,14,PostGame,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56948,2.508378e+09,1,0,0.0,65,0.0,0.0,0,"[{'type': {'value': 194, 'displayName': 'Capta...",[],False,16,PreMatch,34,FormationSet,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56949,2.508378e+09,1,0,0.0,32,0.0,0.0,0,"[{'type': {'value': 194, 'displayName': 'Capta...",[],False,16,PreMatch,34,FormationSet,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN

In [69]:
delete_data = corner_data[(corner_data['type.displayName']== 'CornerAwarded') & (corner_data['outcomeType.displayName']== 'Unsuccessful')].index.tolist()
#corner_data = corner_data.drop(delete_data)
corner_data = corner_data.reset_index(drop=True)
corner_data

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
0,2.443300e+09,2,0,0.0,211,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
1,2.443300e+09,2,0,0.0,32,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
2,2.443300e+09,3,0,0.0,211,50.0,50.0,0,"[{'type': {'value': 213, 'displayName': 'Angle...","[91, 117, 30, 35, 38, 215, 218]",True,1,FirstHalf,1,Pass,1,Successful,21683.0,30.7,46.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adam Lallana
3,2.443300e+09,4,0,3.0,211,31.6,43.4,0,"[{'type': {'value': 1, 'displayName': 'Longbal...","[91, 120, 124, 128, 36, 38, 217, 218]",True,1,FirstHalf,1,Pass,0,Unsuccessful,86441.0,78.3,26.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lewis Dunk
4,2.443300e+09,3,0,6.0,32,20.8,78.7,0,[],[93],False,1,FirstHalf,49,BallRecovery,1,Successful,340105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lisandro Mart√≠nez
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56587,2.508426e+09,892,94,30.0,65,0.0,0.0,97,[],[],False,2,SecondHalf,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56588,2.508426e+09,893,0,0.0,65,0.0,0.0,7,[],[],False,14,PostGame,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56589,2.508427e+09,720,0,0.0,32,0.0,0.0,7,[],[],False,14,PostGame,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56590,2.508378e+09,1,0,0.0,65,0.0,0.0,0,"[{'type': {'value': 194, 'displayName': 'Capta...",[],False,16,PreMatch,34,FormationSet,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56591,2.508378e+09,1,0,0.0,32,0.0,0.0,0,"[{'type': {'value': 194, 'displayName': 'Capta...",[],False,16,PreMatch,34,FormationSet,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN

In [67]:
events_mu = corner_data.loc[corner_data['teamId']==32]
events_mu

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
1,2.443300e+09,2,0,0.0,32,0.0,0.0,0,[],[],False,1,FirstHalf,32,Start,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,2.443300e+09,3,0,6.0,32,20.8,78.7,0,[],[93],False,1,FirstHalf,49,BallRecovery,1,Successful,340105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lisandro Mart√≠nez
5,2.443300e+09,4,0,8.0,32,18.4,63.9,0,"[{'type': {'value': 212, 'displayName': 'Lengt...","[91, 117, 30, 35, 38, 215, 218]",True,1,FirstHalf,1,Pass,1,Successful,340105.0,18.3,37.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lisandro Mart√≠nez
6,2.443300e+09,5,0,10.0,32,17.7,30.4,0,"[{'type': {'value': 213, 'displayName': 'Angle...","[91, 118, 120, 29, 36, 38, 215, 218]",True,1,FirstHalf,1,Pass,0,Unsuccessful,353418.0,19.2,25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Diogo Dalot
8,2.443300e+09,6,0,13.0,32,4.3,33.1,0,"[{'type': {'value': 169, 'displayName': 'Leadi...",[99],False,1,FirstHalf,51,Error,1,Successful,353418.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Diogo Dalot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56941,2.508426e+09,716,93,46.0,32,9.6,94.4,96,"[{'type': {'value': 233, 'displayName': 'Oppos...","[91, 142]",True,2,SecondHalf,7,Tackle,0,Unsuccessful,123761.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Bruno Fernandes
56942,2.508426e+09,717,93,47.0,32,9.0,92.0,96,"[{'type': {'value': 13, 'displayName': 'Foul'}...","[91, 63]",True,2,SecondHalf,4,Foul,1,Successful,123761.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Bruno Fernandes
56944,2.508426e+09,719,94,30.0,32,0.0,0.0,97,[],[],False,2,SecondHalf,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56947,2.508427e+09,720,0,0.0,32,0.0,0.0,7,[],[],False,14,PostGame,30,End,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN
56949,2.508378e+09,1,0,0.0,32,0.0,0.0,0,"[{'type': {'value': 194, 'displayName': 'Capta...",[],False,16,PreMatch,34,FormationSet,1,Successful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,NaN

In [74]:
index = events_mu[(events_mu['type.displayName']== 'CornerAwarded') & (events_mu['outcomeType.displayName']== 'Successful') ].index.tolist()
index2 = [x+2 for x in index]

In [80]:
x = pd.DataFrame(corner_data['qualifiers'])
x

                                              qualifiers
0                                                     []
1                                                     []
2      [{'type': {'value': 213, 'displayName': 'Angle...
3      [{'type': {'value': 1, 'displayName': 'Longbal...
4                                                     []
...                                                  ...
56587                                                 []
56588                                                 []
56589                                                 []
56590  [{'type': {'value': 194, 'displayName': 'Capta...
56591  [{'type': {'value': 194, 'displayName': 'Capta...

[56592 rows x 1 columns]

In [78]:
corner_data['qualifiers']

0                                                       []
1                                                       []
2        [{'type': {'value': 213, 'displayName': 'Angle...
3        [{'type': {'value': 1, 'displayName': 'Longbal...
4                                                       []
                               ...
56587                                                   []
56588                                                   []
56589                                                   []
56590    [{'type': {'value': 194, 'displayName': 'Capta...
56591    [{'type': {'value': 194, 'displayName': 'Capta...
Name: qualifiers, Length: 56592, dtype: object

In [36]:
events_all.loc[index]

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
408,2.443331e+09,261,27,52.0,32,26.0,47.2,27,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,1,FirstHalf,6,CornerAwarded,0,Unsuccessful,69344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Christian Eriksen
871,2.443359e+09,549,55,5.0,32,96.0,63.0,58,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,123761.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Bruno Fernandes
876,2.443359e+09,552,55,18.0,32,92.0,76.0,58,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,69344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Christian Eriksen
958,2.443364e+09,599,61,36.0,32,6.9,24.3,64,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,353418.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Diogo Dalot
1048,2.443368e+09,639,66,40.0,32,89.2,44.1,69,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,69344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Christian Eriksen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56422,2.508414e+09,466,57,57.0,32,89.8,32.5,60,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,300299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Marcus Rashford
56455,2.508416e+09,482,60,57.0,32,91.6,39.0,63,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,331924.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Aaron Wan-Bissaka
56707,2.508422e+09,603,79,19.0,32,10.0,50.8,82,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,79554.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,David de Gea
56917,2.508426e+09,707,92,20.0,32,0.0,41.4,95,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,88526.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Casemiro
56932,2.508426e+09,713,93,12.0,32,3.1,57.0,96,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,345303.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Tyrell Malacia

In [10]:
events_mu.loc[events_mu['type.displayName']=='CornerAwarded']

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
408,2.443331e+09,261,27,52.0,32,26.0,47.2,27,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,1,FirstHalf,6,CornerAwarded,0,Unsuccessful,69344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Christian Eriksen
871,2.443359e+09,549,55,5.0,32,96.0,63.0,58,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,123761.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Bruno Fernandes
876,2.443359e+09,552,55,18.0,32,92.0,76.0,58,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,69344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Christian Eriksen
958,2.443364e+09,599,61,36.0,32,6.9,24.3,64,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,353418.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Diogo Dalot
1048,2.443368e+09,639,66,40.0,32,89.2,44.1,69,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,69344.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Christian Eriksen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56422,2.508414e+09,466,57,57.0,32,89.8,32.5,60,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,300299.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Marcus Rashford
56455,2.508416e+09,482,60,57.0,32,91.6,39.0,63,"[{'type': {'value': 56, 'displayName': 'Zone'}...",[122],False,2,SecondHalf,6,CornerAwarded,1,Successful,331924.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Aaron Wan-Bissaka
56707,2.508422e+09,603,79,19.0,32,10.0,50.8,82,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,79554.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,David de Gea
56917,2.508426e+09,707,92,20.0,32,0.0,41.4,95,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,88526.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Casemiro
56932,2.508426e+09,713,93,12.0,32,3.1,57.0,96,"[{'type': {'value': 233, 'displayName': 'Oppos...",[122],False,2,SecondHalf,6,CornerAwarded,0,Unsuccessful,345303.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,Tyrell Malacia

In [6]:
events_all['type.displayName'].unique()

array(['Start', 'Pass', 'BallRecovery', 'BlockedPass', 'Error',
       'MissedShots', 'Interception', 'BallTouch', 'Dispossessed',
       'Tackle', 'Foul', 'OffsideGiven', 'OffsidePass', 'OffsideProvoked',
       'SavedShot', 'Save', 'TakeOn', 'Challenge', 'Clearance',
       'KeeperPickup', 'Card', 'CornerAwarded', 'Aerial', 'Goal',
       'ShieldBallOpp', 'End', 'SubstitutionOff', 'SubstitutionOn',
       'FormationChange', 'CrossNotClaimed', 'Punch', 'KeeperSweeper',
       'FormationSet', 'Claim', 'ShotOnPost', 'PenaltyFaced', 'Smother',
       'GoodSkill'], dtype=object)

# Shots

In [13]:
all_shots = events_all.loc[(events_all['type.displayName']=="MissedShots")|(events_all['type.displayName']=="SavedShot")|(events_all['type.displayName']=="Goal")]
all_shots

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
10,2.443300e+09,7,0,13.0,211,94.7,70.2,0,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 7, 90, 10, 88, 1, 3, 13]",True,1,FirstHalf,13,MissedShots,1,Successful,113994.0,NaN,NaN,16.7,57.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Leandro Trossard
87,2.443308e+09,63,6,2.0,32,92.6,32.8,6,"[{'type': {'value': 82, 'displayName': 'Blocke...","[91, 10, 1, 3, 11, 12]",True,1,FirstHalf,15,SavedShot,1,Successful,336915.0,NaN,NaN,19.0,52.6,True,62.0,346300.0,93.6,35.4,NaN,NaN,NaN,NaN,1,Scott McTominay
89,2.443308e+09,64,6,3.0,32,86.8,54.5,6,"[{'type': {'value': 74, 'displayName': 'MissHi...","[91, 7, 90, 10, 1, 3, 12]",True,1,FirstHalf,13,MissedShots,1,Successful,123761.0,NaN,NaN,95.8,44.9,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Bruno Fernandes
210,2.443316e+09,83,13,2.0,211,79.1,38.0,13,"[{'type': {'value': 72, 'displayName': 'LeftFo...","[91, 10, 2, 3, 11, 13]",True,1,FirstHalf,15,SavedShot,1,Successful,39308.0,NaN,NaN,19.0,50.8,True,86.0,21683.0,80.7,39.0,NaN,NaN,NaN,NaN,1,Danny Welbeck
283,2.443321e+09,132,17,51.0,211,69.4,72.1,17,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 10, 2, 3, 11, 12]",True,1,FirstHalf,15,SavedShot,1,Successful,113994.0,NaN,NaN,19.0,46.4,True,130.0,410175.0,80.5,62.8,NaN,NaN,NaN,NaN,1,Leandro Trossard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47494,2.500638e+09,865,77,29.0,32,74.4,64.9,79,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 7, 10, 2, 3, 12]",True,2,SecondHalf,13,MissedShots,1,Successful,114397.0,NaN,NaN,66.7,44.4,True,864.0,88526.0,NaN,NaN,NaN,NaN,NaN,NaN,31,Fred
47508,2.500638e+09,872,78,38.0,32,91.9,47.6,80,"[{'type': {'value': 154, 'displayName': 'Inten...","[91, 7, 90, 10, 1, 3, 14]",True,2,SecondHalf,13,MissedShots,1,Successful,115479.0,NaN,NaN,2.8,82.0,True,870.0,404086.0,NaN,NaN,NaN,NaN,NaN,NaN,31,Wout Weghorst
47606,2.500640e+09,623,86,32.0,174,87.9,51.5,88,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 10, 1, 5, 11, 14]",True,2,SecondHalf,15,SavedShot,1,Successful,315714.0,NaN,NaN,19.0,51.1,True,621.0,386969.0,89.5,51.4,NaN,NaN,NaN,NaN,31,Joe Worrall
47643,2.500640e+09,964,88,6.0,32,84.2,41.3,90,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,123761.0,NaN,NaN,3.2,52.7,True,963.0,413211.0,NaN,NaN,NaN,NaN,True,NaN,31,Bruno Fernandes
47705,2.500641e+09,665,92,45.0,174,84.9,38.6,94,"[{'type': {'value': 233, 'displayName': 'Oppos...","[91, 10, 1, 3, 11, 12]",True,2,SecondHalf,15,SavedShot,1,Successful,329811.0,NaN,NaN,19.0,46.7,True,664.0,83683.0,88.0,40.2,NaN,NaN,NaN,NaN,31,Emmanuel Dennis

In [16]:
mu_shots = events_mu.loc[(events_mu['type.displayName']=="MissedShots")|(events_mu['type.displayName']=="SavedShot")|(events_mu['type.displayName']=="Goal")]
mu_shots = mu_shots.reset_index(drop=True)
mu_shots

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
0,2.443308e+09,63,6,2.0,32,92.6,32.8,6,"[{'type': {'value': 82, 'displayName': 'Blocke...","[91, 10, 1, 3, 11, 12]",True,1,FirstHalf,15,SavedShot,1,Successful,336915.0,NaN,NaN,19.0,52.6,True,62.0,346300.0,93.6,35.4,NaN,NaN,NaN,NaN,1,Scott McTominay
1,2.443308e+09,64,6,3.0,32,86.8,54.5,6,"[{'type': {'value': 74, 'displayName': 'MissHi...","[91, 7, 90, 10, 1, 3, 12]",True,1,FirstHalf,13,MissedShots,1,Successful,123761.0,NaN,NaN,95.8,44.9,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Bruno Fernandes
2,2.443327e+09,243,23,21.0,32,91.6,70.2,23,"[{'type': {'value': 178, 'displayName': 'Stand...","[91, 9, 10, 1, 3, 13]",True,1,FirstHalf,15,SavedShot,1,Successful,69344.0,NaN,NaN,24.1,51.2,True,242.0,123761.0,98.0,55.2,NaN,NaN,NaN,NaN,1,Christian Eriksen
3,2.443335e+09,319,34,41.0,32,75.1,64.6,34,"[{'type': {'value': 18, 'displayName': 'OutOfB...","[91, 7, 10, 2, 3, 13]",True,1,FirstHalf,13,MissedShots,1,Successful,114397.0,NaN,NaN,55.6,61.3,True,318.0,300299.0,NaN,NaN,NaN,NaN,NaN,NaN,1,Fred
4,2.443343e+09,401,44,29.0,32,95.9,63.9,44,"[{'type': {'value': 72, 'displayName': 'LeftFo...","[91, 9, 10, 1, 3, 13]",True,1,FirstHalf,15,SavedShot,1,Successful,118244.0,NaN,NaN,2.5,51.9,True,NaN,NaN,99.3,54.3,NaN,NaN,NaN,NaN,1,Luke Shaw
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,2.500626e+09,602,50,49.0,32,87.1,42.8,52,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 7, 90, 10, 1, 3, 13]",True,2,SecondHalf,13,MissedShots,1,Successful,123761.0,NaN,NaN,63.9,73.8,True,601.0,345303.0,NaN,NaN,NaN,NaN,NaN,NaN,31,Bruno Fernandes
455,2.500628e+09,638,53,20.0,32,75.1,67.0,55,"[{'type': {'value': 147, 'displayName': 'Block...","[91, 9, 10, 2, 3, 12]",True,2,SecondHalf,15,SavedShot,1,Successful,300299.0,NaN,NaN,18.4,54.3,True,637.0,364315.0,98.9,50.0,NaN,NaN,NaN,NaN,31,Marcus Rashford
456,2.500638e+09,865,77,29.0,32,74.4,64.9,79,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 7, 10, 2, 3, 12]",True,2,SecondHalf,13,MissedShots,1,Successful,114397.0,NaN,NaN,66.7,44.4,True,864.0,88526.0,NaN,NaN,NaN,NaN,NaN,NaN,31,Fred
457,2.500638e+09,872,78,38.0,32,91.9,47.6,80,"[{'type': {'value': 154, 'displayName': 'Inten...","[91, 7, 90, 10, 1, 3, 14]",True,2,SecondHalf,13,MissedShots,1,Successful,115479.0,NaN,NaN,2.8,82.0,True,870.0,404086.0,NaN,NaN,NaN,NaN,NaN,NaN,31,Wout Weghorst
458,2.500640e+09,964,88,6.0,32,84.2,41.3,90,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,123761.0,NaN,NaN,3.2,52.7,True,963.0,413211.0,NaN,NaN,NaN,NaN,True,NaN,31,Bruno Fernandes

In [28]:
shot_goal = mu_shots.loc[mu_shots.isGoal==True].reset_index(drop=True)
shot_goal

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
0,2.449983e+09,145,15,5.0,32,89.2,52.4,15,"[{'type': {'value': 214, 'displayName': 'BigCh...","[91, 24, 9, 10, 202, 1, 3, 12, 17, 19, 25]",True,1,FirstHalf,16,Goal,1,Successful,346300.0,NaN,NaN,3.2,53.8,True,143.0,413211.0,NaN,NaN,NaN,NaN,True,NaN,3,Jadon Sancho
1,2.450005e+09,406,52,26.0,32,83.5,59.0,53,"[{'type': {'value': 55, 'displayName': 'Relate...","[91, 24, 9, 10, 202, 1, 4, 12, 17, 20, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,9.5,54.0,True,405.0,122366.0,NaN,NaN,NaN,NaN,True,NaN,3,Marcus Rashford
2,2.451430e+09,546,54,20.0,32,85.2,53.8,55,"[{'type': {'value': 154, 'displayName': 'Inten...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,123761.0,NaN,NaN,0.6,54.3,True,545.0,353418.0,NaN,NaN,NaN,NaN,True,NaN,4,Bruno Fernandes
3,2.454270e+09,243,22,4.0,32,92.9,40.9,22,"[{'type': {'value': 103, 'displayName': 'GoalM...","[91, 24, 9, 10, 202, 1, 4, 12, 17, 20, 25]",True,1,FirstHalf,16,Goal,1,Successful,346300.0,NaN,NaN,1.3,46.8,True,242.0,300299.0,NaN,NaN,NaN,NaN,True,NaN,5,Jadon Sancho
4,2.455902e+09,276,34,21.0,32,92.5,34.4,34,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 202, 1, 3, 13, 17, 19, 26]",True,1,FirstHalf,16,Goal,1,Successful,364315.0,NaN,NaN,5.7,53.0,True,275.0,300299.0,NaN,NaN,NaN,NaN,True,NaN,6,Antony
5,2.455940e+09,459,65,3.0,32,81.8,46.6,69,"[{'type': {'value': 55, 'displayName': 'Relate...","[91, 24, 9, 10, 202, 2, 3, 12, 18, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,3.8,54.5,True,458.0,123761.0,NaN,NaN,NaN,NaN,True,NaN,6,Marcus Rashford
6,2.455946e+09,531,74,50.0,32,93.0,55.9,78,"[{'type': {'value': 154, 'displayName': 'Inten...","[91, 24, 9, 10, 202, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,17.1,50.0,True,530.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,6,Marcus Rashford
7,2.460213e+09,199,16,44.0,32,87.0,54.7,16,"[{'type': {'value': 72, 'displayName': 'LeftFo...","[91, 24, 9, 10, 1, 3, 13, 17, 19, 26]",True,1,FirstHalf,16,Goal,1,Successful,346300.0,NaN,NaN,1.9,45.7,True,197.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,8,Jadon Sancho
8,2.460227e+09,396,38,46.0,32,88.5,50.0,38,"[{'type': {'value': 9, 'displayName': 'Penalty...","[91, 22, 9, 10, 202, 1, 12, 17, 25]",True,1,FirstHalf,16,Goal,1,Successful,5583.0,NaN,NaN,14.6,50.3,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,8,Cristiano Ronaldo
9,2.466508e+09,436,55,29.0,32,77.1,37.7,58,"[{'type': {'value': 103, 'displayName': 'GoalM...","[91, 24, 9, 10, 2, 3, 13, 18, 19, 26]",True,2,SecondHalf,16,Goal,1,Successful,364315.0,NaN,NaN,18.4,54.3,True,435.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,9,Antony
10,2.466537e+09,680,83,6.0,32,95.8,50.4,86,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 202, 0, 3, 14, 16, 19, 27]",True,2,SecondHalf,16,Goal,1,Successful,122366.0,NaN,NaN,7.6,46.8,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,9,Anthony Martial
11,2.466545e+09,733,90,1.0,32,88.5,50.0,93,"[{'type': {'value': 214, 'displayName': 'BigCh...","[91, 22, 9, 10, 202, 1, 12, 17, 25]",True,2,SecondHalf,16,Goal,1,Successful,122366.0,NaN,NaN,32.3,45.6,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,9,Anthony Martial
12,2.468037e+09,637,52,3.0,32,81.6,60.2,55,"[{'type': {'value': 20, 'displayName': 'RightF...","[91, 24, 9, 10, 2, 3, 12, 18, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,13.3,46.0,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,10,Marcus Rashford
13,2.468044e+09,770,62,19.0,32,81.6,60.4,65,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 24, 9, 10, 2, 3, 12, 18, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,122366.0,NaN,NaN,5.7,53.9,True,769.0,300299.0,NaN,NaN,NaN,NaN,True,NaN,10,Anthony Martial
14,2.468059e+09,993,83,24.0,32,97.5,46.0,86,"[{'type': {'value': 20, 'displayName': 'RightF...","[91, 24, 9, 10, 202, 0, 4, 12, 16, 20, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,0.6,49.1,True,992.0,5583.0,NaN,NaN,NaN,NaN,True,NaN,10,Marcus Rashford
15,2.469923e+09,197,14,5.0,32,86.8,38.3,14,"[{'type': {'value': 23, 'displayName': 'FastBr...","[91, 24, 9, 10, 202, 1, 4, 13, 17, 20, 26]",True,1,FirstHalf,16,Goal,1,Successful,364315.0,NaN,NaN,5.1,54.2,True,196.0,122366.0,NaN,NaN,NaN,NaN,True,NaN,11,Antony
16,2.469940e+09,534,43,27.0,32,89.6,70.1,43,"[{'type': {'value': 23, 'displayName': 'FastBr...","[91, 24, 9, 10, 202, 1, 4, 13, 17, 20, 26]",True,1,FirstHalf,16,Goal,1,Successful,5583.0,NaN,NaN,1.9,51.4,True,533.0,88526.0,NaN,NaN,NaN,NaN,True,NaN,11,Cristiano Ronaldo
17,2.471414e+09,1131,92,27.0,32,90.6,51.5,93,"[{'type': {'value': 178, 'displayName': 'Stand...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,336915.0,NaN,NaN,3.8,52.0,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,12,Scott McTominay
18,2.474415e+09,478,46,16.0,32,80.1,50.1,49,"[{'type': {'value': 29, 'displayName': 'Assist...","[91, 24, 9, 10, 2, 3, 13, 18, 19, 26]",True,2,SecondHalf,16,Goal,1,Successful,114397.0,NaN,NaN,7.0,53.9,True,477.0,346300.0,NaN,NaN,NaN,NaN,True,NaN,14,Fred
19,2.474432e+09,681,68,11.0,32,84.5,54.3,71,"[{'type': {'value': 80, 'displayName': 'LowRig...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,123761.0,NaN,NaN,17.7,46.1,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,14,Bruno Fernandes
20,2.475764e+09,824,93,25.0,32,90.0,43.9,95,"[{'type': {'value': 17, 'displayName': 'BoxCen...","[91, 24, 9, 10, 1, 3, 14, 17, 19, 27]",True,2,SecondHalf,16,Goal,1,Successful,88526.0,NaN,NaN,3.2,53.2,True,823.0,118244.0,NaN,NaN,NaN,NaN,True,NaN,15,Casemiro
21,2.478036e+09,500,43,13.0,32,95.2,56.1,43,"[{'type': {'value': 15, 'displayName': 'Head'}...","[91, 24, 9, 10, 202, 0, 5, 14, 16, 21, 27]",True,1,FirstHalf,16,Goal,1,Successful,353418.0,NaN,NaN,7.0,46.0,True,498.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,16,Diogo Dalot
22,2.478053e+09,730,64,22.0,32,89.5,55.5,66,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 24, 9, 10, 1, 3, 14, 17, 19, 27]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,24.7,53.9,True,729.0,118244.0,NaN,NaN,NaN,NaN,True,NaN,16,Marcus Rashford
23,2.478063e+09,897,80,45.0,32,97.7,56.3,82,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 24, 9, 10, 202, 0, 3, 13, 16, 19, 26]",True,2,SecondHalf,16,Goal,1,Successful,5583.0,NaN,NaN,22.8,53.9,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,16,Cristiano Ronaldo
24,2.479661e+09,374,37,45.0,32,95.1,53.4,37,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 202, 0, 3, 14, 16, 19, 27]",True,1,FirstHalf,16,Goal,1,Successful,300299.0,NaN,NaN,29.7,48.5,True,373.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,17,Marcus Rashford
25,2.480972e+09,158,16,37.0,32,94.2,67.8,16,"[{'type': {'value': 72, 'displayName': 'LeftFo...","[91, 24, 9, 10, 202, 1, 3, 13, 17, 19, 26]",True,1,FirstHalf,16,Goal,1,Successful,437022.0,NaN,NaN,31.6,48.7,True,157.0,5583.0,NaN,NaN,NaN,NaN,True,NaN,18,Alejandro Garnacho
26,2.484065e+09,463,48,40.0,32,93.0,53.8,50,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 24, 9, 10, 202, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,122366.0,NaN,NaN,0.6,52.9,True,462.0,123761.0,NaN,NaN,NaN,NaN,True,NaN,20,Anthony Martial
27,2.484067e+09,563,60,25.0,32,2.3,46.4,62,"[{'type': {'value': 81, 'displayName': 'HighRi...","[91, 23]",True,2,SecondHalf,16,Goal,1,Successful,353418.0,NaN,NaN,26.6,47.7,True,NaN,NaN,NaN,NaN,NaN,NaN,True,True,20,Diogo Dalot
28,2.484068e+09,641,66,32.0,32,92.0,45.4,68,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 24, 9, 10, 202, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,1.3,46.1,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,20,Marcus Rashford
29,2.484069e+09,747,77,52.0,32,85.3,53.4,79,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,123761.0,NaN,NaN,25.9,54.2,True,746.0,437022.0,NaN,NaN,NaN,NaN,True,NaN,20,Bruno Fernandes
30,2.484070e+09,833,90,21.0,32,93.2,49.8,92,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 24, 9, 10, 202, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,336915.0,NaN,NaN,4.4,51.9,True,832.0,437022.0,NaN,NaN,NaN,NaN,True,NaN,20,Scott McTominay
31,2.485438e+09,153,13,47.0,32,96.5,47.2,13,"[{'type': {'value': 23, 'displayName': 'FastBr...","[91, 24, 9, 10, 202, 0, 4, 12, 16, 20, 25]",True,1,FirstHalf,16,Goal,1,Successful,69344.0,NaN,NaN,5.1,47.3,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,21,Christian Eriksen
32,2.485507e+09,816,92,4.0,32,92.4,62.4,94,"[{'type': {'value': 154, 'displayName': 'Inten...","[91, 24, 9, 10, 202, 1, 3, 13, 17, 19, 26]",True,2,SecondHalf,16,Goal,1,Successful,437022.0,NaN,NaN,1.3,47.2,True,815.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,21,Alejandro Garnacho
33,2.492713e+09,262,26,3.0,32,96.9,49.8,26,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 202, 0, 3, 12, 16, 19, 25]",True,1,FirstHalf,16,Goal,1,Successful,69344.0,NaN,NaN,25.9,50.4,True,261.0,331924.0,NaN,NaN,NaN,NaN,True,NaN,22,Christian Eriksen
34,2.492731e+09,554,56,44.0,32,89.9,33.2,58,"[{'type': {'value': 178, 'displayName': 'Stand...","[91, 24, 9, 10, 1, 4, 12, 17, 20, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,3.8,54.1,True,551.0,336915.0,NaN,NaN,NaN,NaN,True,NaN,22,Marcus Rashford
35,2.493599e+09,239,18,57.0,32,89.5,41.9,18,"[{'type': {'value': 178, 'displayName': 'Stand...","[91, 24, 9, 10, 1, 5, 12, 17, 21, 25]",True,1,FirstHalf,16,Goal,1,Successful,300299.0,NaN,NaN,29.7,51.6,True,238.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,23,Marcus Rashford
36,2.493599e+09,266,22,1.0,32,84.0,46.8,22,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 24, 9, 10, 1, 4, 12, 17, 20, 25]",True,1,FirstHalf,16,Goal,1,Successful,122366.0,NaN,NaN,2.5,54.0,True,265.0,300299.0,NaN,NaN,NaN,NaN,True,NaN,23,Anthony Martial
37,2.493609e+09,925,86,32.0,32,91.5,61.4,89,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 24, 9, 10, 202, 1, 3, 13, 17, 19, 26]",True,2,SecondHalf,16,Goal,1,Successful,114397.0,NaN,NaN,14.6,45.8,True,924.0,88526.0,NaN,NaN,NaN,NaN,True,NaN,23,Fred
38,2.494338e+09,701,75,54.0,32,92.5,55.8,77,"[{'type': {'value': 29, 'displayName': 'Assist...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,3.2,51.0,True,699.0,123761.0,NaN,NaN,NaN,NaN,True,NaN,24,Marcus Rashford
39,2.494911e+09,268,22,33.0,32,92.9,52.8,22,"[{'type': {'value': 29, 'displayName': 'Assist...","[91, 24, 9, 10, 202, 1, 5, 12, 17, 21, 25]",True,1,FirstHalf,16,Goal,1,Successful,88526.0,NaN,NaN,27.2,54.0,True,267.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,25,Casemiro
40,2.494920e+09,522,48,26.0,32,89.1,47.8,51,"[{'type': {'value': 55, 'displayName': 'Relate...","[91, 24, 9, 10, 202, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,118244.0,NaN,NaN,2.5,53.3,True,521.0,437022.0,NaN,NaN,NaN,NaN,True,NaN,25,Luke Shaw
41,2.494930e+09,846,85,22.0,32,95.7,55.3,88,"[{'type': {'value': 154, 'displayName': 'Inten...","[91, 24, 9, 10, 202, 0, 3, 13, 16, 19, 26]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,2.5,52.3,True,845.0,123761.0,NaN,NaN,NaN,NaN,True,NaN,25,Marcus Rashford
42,2.495368e+09,49,3,2.0,32,97.0,46.0,3,"[{'type': {'value': 80, 'displayName': 'LowRig...","[91, 24, 9, 10, 202, 0, 3, 12, 16, 19, 25]",True,1,FirstHalf,16,Goal,1,Successful,364315.0,NaN,NaN,1.9,46.1,True,48.0,300299.0,NaN,NaN,NaN,NaN,True,NaN,26,Antony
43,2.495410e+09,833,96,26.0,32,88.5,50.0,98,"[{'type': {'value': 9, 'displayName': 'Penalty...","[91, 22, 9, 10, 202, 1, 12, 17, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,1.9,46.3,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,26,Marcus Rashford
44,2.496426e+09,199,20,36.0,32,79.4,28.5,20,"[{'type': {'value': 72, 'displayName': 'LeftFo...","[91, 24, 9, 10, 2, 3, 13, 18, 19, 26]",True,1,FirstHalf,16,Goal,1,Successful,364315.0,NaN,NaN,22.2,53.8,True,198.0,114397.0,NaN,NaN,NaN,NaN,True,NaN,27,Antony
45,2.496474e+09,963,89,3.0,32,91.4,56.7,92,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 24, 9, 10, 202, 1, 4, 12, 17, 20, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,2.5,53.3,True,962.0,404086.0,NaN,NaN,NaN,NaN,True,NaN,27,Marcus Rashford
46,2.496475e+09,1003,93,37.0,32,88.0,64.5,96,"[{'type': {'value': 72, 'displayName': 'LeftFo...","[91, 24, 9, 10, 202, 1, 3, 13, 17, 19, 26]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,22.8,51.8,True,1002.0,88526.0,NaN,NaN,NaN,NaN,True,NaN,27,Marcus Rashford
47,2.497175e+09,506,77,59.0,32,81.5,49.3,78,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 24, 9, 10, 202, 2, 3, 12, 18, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,123761.0,NaN,NaN,7.0,49.4,True,505.0,88526.0,NaN,NaN,NaN,NaN,True,NaN,28,Bruno Fernandes
48,2.497177e+09,523,81,45.0,32,95.7,52.6,82,"[{'type': {'value': 214, 'displayName': 'BigCh...","[91, 24, 9, 10, 202, 0, 3, 12, 16, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,300299.0,NaN,NaN,1.3,50.1,True,522.0,437022.0,NaN,NaN,NaN,NaN,True,NaN,28,Marcus Rashford
49,2.498528e+09,486,43,1.0,32,87.4,53.8,43,"[{'type': {'value': 178, 'displayName': 'Stand...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,1,FirstHalf,16,Goal,1,Successful,123761.0,NaN,NaN,20.9,47.1,True,485.0,69344.0,NaN,NaN,NaN,NaN,True,NaN,29,Bruno Fernandes
50,2.499776e+09,181,16,49.0,32,76.2,61.2,16,"[{'type': {'value': 29, 'displayName': 'Assist...","[91, 24, 9, 10, 2, 3, 12, 18, 19, 25]",True,1,FirstHalf,16,Goal,1,Successful,300299.0,NaN,NaN,6.3,54.1,True,179.0,123761.0,NaN,NaN,NaN,NaN,True,NaN,30,Marcus Rashford
51,2.499807e+09,533,58,23.0,32,91.6,53.4,61,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 24, 9, 10, 1, 5, 14, 17, 21, 27]",True,2,SecondHalf,16,Goal,1,Successful,340105.0,NaN,NaN,29.7,48.8,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,30,Lisandro Mart√≠nez
52,2.500597e+09,71,5,23.0,32,91.1,61.1,5,"[{'type': {'value': 154, 'displayName': 'Inten...","[91, 24, 9, 10, 1, 3, 13, 17, 19, 26]",True,1,FirstHalf,16,Goal,1,Successful,300299.0,NaN,NaN,15.2,53.8,True,69.0,88526.0,NaN,NaN,NaN,NaN,True,NaN,31,Marcus Rashford
53,2.500615e+09,495,44,30.0,32,91.6,45.4,44,"[{'type': {'value': 102, 'displayName': 'GoalM...","[91, 24, 9, 10, 202, 1, 3, 12, 17, 19, 25]",True,1,FirstHalf,16,Goal,1,Successful,115479.0,NaN,NaN,32.9,50.3,True,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,31,Wout Weghorst
54,2.500640e+09,964,88,6.0,32,84.2,41.3,90,"[{'type': {'value': 22, 'displayName': 'Regula...","[91, 24, 9, 10, 1, 3, 12, 17, 19, 25]",True,2,SecondHalf,16,Goal,1,Successful,123761.0,NaN,NaN,3.2,52.7,True,963.0,413211.0,NaN,NaN,NaN,NaN,True,NaN,31,Bruno Fernandes

In [54]:
goalscorer = pd.DataFrame(shot_goal['player_name'].value_counts())
goalscorer.columns=['Goals']
goalscorer

                    Goals
Marcus Rashford        18
Bruno Fernandes         6
Antony                  5
Anthony Martial         5
Jadon Sancho            3
Cristiano Ronaldo       3
Scott McTominay         2
Fred                    2
Casemiro                2
Diogo Dalot             2
Alejandro Garnacho      2
Christian Eriksen       2
Luke Shaw               1
Lisandro Mart√≠nez       1
Wout Weghorst           1

In [40]:
goalscorer = pd.DataFrame(shot_goal.groupby("player_name").size(),columns=['Goals']).sort_values('Goals',ascending=False)
goalscorer

                    Goals
player_name
Marcus Rashford        18
Bruno Fernandes         6
Anthony Martial         5
Antony                  5
Cristiano Ronaldo       3
Jadon Sancho            3
Alejandro Garnacho      2
Casemiro                2
Christian Eriksen       2
Diogo Dalot             2
Fred                    2
Scott McTominay         2
Lisandro Mart√≠nez       1
Luke Shaw               1
Wout Weghorst           1

# Next Task
- Check who pass before goal or shot happened
- Check key passes
- Try to visualize shot map
- Check which area that most shots taken
- Try to visualize Passing network

In [10]:
events_all.loc[events_all['type.displayName']=="Pass"]

,id,eventId,minute,second,teamId,x,y,expandedMinute,qualifiers,satisfiedEventsTypes,isTouch,period.value,period.displayName,type.value,type.displayName,outcomeType.value,outcomeType.displayName,playerId,endX,endY,goalMouthZ,goalMouthY,isShot,relatedEventId,relatedPlayerId,blockedX,blockedY,cardType.value,cardType.displayName,isGoal,isOwnGoal,matchId,player_name
2,2.443300e+09,3,0,0.0,211,50.0,50.0,0,"[{'type': {'value': 213, 'displayName': 'Angle...","[91, 117, 30, 35, 38, 215, 218]",True,1,FirstHalf,1,Pass,1,Successful,21683.0,30.7,46.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adam Lallana
3,2.443300e+09,4,0,3.0,211,31.6,43.4,0,"[{'type': {'value': 1, 'displayName': 'Longbal...","[91, 120, 124, 128, 36, 38, 217, 218]",True,1,FirstHalf,1,Pass,0,Unsuccessful,86441.0,78.3,26.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lewis Dunk
5,2.443300e+09,4,0,8.0,32,18.4,63.9,0,"[{'type': {'value': 212, 'displayName': 'Lengt...","[91, 117, 30, 35, 38, 215, 218]",True,1,FirstHalf,1,Pass,1,Successful,340105.0,18.3,37.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lisandro Mart√≠nez
6,2.443300e+09,5,0,10.0,32,17.7,30.4,0,"[{'type': {'value': 213, 'displayName': 'Angle...","[91, 118, 120, 29, 36, 38, 215, 218]",True,1,FirstHalf,1,Pass,0,Unsuccessful,353418.0,19.2,25.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Diogo Dalot
11,2.443522e+09,939,0,36.0,32,4.4,59.4,0,"[{'type': {'value': 141, 'displayName': 'PassE...","[91, 117, 30, 35, 38, 215, 218]",True,1,FirstHalf,1,Pass,1,Successful,340105.0,2.4,48.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Lisandro Mart√≠nez
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47700,2.500641e+09,1000,92,29.0,32,43.3,68.4,94,"[{'type': {'value': 140, 'displayName': 'PassE...","[91, 120, 29, 36, 37, 216, 218]",True,2,SecondHalf,1,Pass,0,Unsuccessful,123761.0,55.2,69.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,Bruno Fernandes
47702,2.500641e+09,662,92,34.0,174,57.3,51.5,94,"[{'type': {'value': 56, 'displayName': 'Zone'}...","[91, 117, 30, 35, 37, 216, 218]",True,2,SecondHalf,1,Pass,1,Successful,315714.0,45.1,55.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,Joe Worrall
47703,2.500641e+09,663,92,36.0,174,45.1,55.8,94,"[{'type': {'value': 213, 'displayName': 'Angle...","[91, 119, 117, 124, 127, 205, 36, 38, 217, 218]",True,2,SecondHalf,1,Pass,1,Successful,364624.0,74.8,3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,Scott McKenna
47704,2.500641e+09,664,92,42.0,174,77.5,7.7,94,"[{'type': {'value': 212, 'displayName': 'Lengt...","[91, 119, 117, 30, 123, 205, 40, 46, 36, 37, 2...",True,2,SecondHalf,1,Pass,1,Successful,83683.0,84.5,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,Serge Aurier
47709,2.500641e+09,667,93,0.0,174,99.5,0.5,95,"[{'type': {'value': 140, 'displayName': 'PassE...","[91, 137, 126, 31, 33, 34, 35, 37, 217, 218]",True,2,SecondHalf,1,Pass,0,Unsuccessful,109000.0,92.1,37.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,Jesse Lingard

In [11]:
events_all['outcomeType.displayName'].value_counts()

Successful      37439
Unsuccessful    10280
Name: outcomeType.displayName, dtype: int64

In [14]:
pass_percentange = 37439/(37439+10280)*100
pass_percentange

78.45721829879085

In [12]:
player_list

     playerId         player_name
0      340105   Lisandro Mart√≠nez
1      437022  Alejandro Garnacho
2      114397                Fred
3       69344   Christian Eriksen
4       93206      Rapha√´l Varane
..        ...                 ...
519    115479       Wout Weghorst
520    238940       Thomas Partey
521    149738      Gustavo Scarpa
522    332867  Morgan Gibbs-White
523    399250              Danilo

[524 rows x 2 columns]

# Casemiro Dispossessed, Pass Outcome, Defensive Action

In [5]:
player_list.loc[player_list['player_name']=='Casemiro']

     playerId player_name
101   88526.0    Casemiro

In [6]:
case_events = events_all.loc[events_all.playerId==88526]

In [7]:
case_pass = case_events.loc[case_events['type.displayName']=='Pass']
case_dispossesed = case_events.loc[case_events['type.displayName']=='Dispossessed']
case_intercept = case_events.loc[case_events['type.displayName']=='Interception']
case_tackle = case_events.loc[case_events['type.displayName']=='Tackle']

In [8]:
pass_outcome = case_pass['outcomeType.displayName'].value_counts()
pass_total = pass_outcome['Successful'] + pass_outcome['Unsuccessful']

In [9]:
pass_outcome

Successful      1150
Unsuccessful     294
Name: outcomeType.displayName, dtype: int64

In [10]:
pass_percentange = (pass_outcome['Successful']/pass_total)*100
pass_percentange

79.6398891966759

# McTominay Dispossessed, Pass Outcome, Defensive Action

In [11]:
player_list.loc[player_list['player_name']=='Scott McTominay']

    playerId      player_name
19  336915.0  Scott McTominay

In [12]:
mctom_events = events_all.loc[events_all.playerId==336915]

In [13]:
mctom_pass = mctom_events.loc[mctom_events['type.displayName']=='Pass']
mctom_dispossesed = mctom_events.loc[mctom_events['type.displayName']=='Dispossessed']
mctom_intercept = mctom_events.loc[mctom_events['type.displayName']=='Interception']
mctom_tackle = mctom_events.loc[mctom_events['type.displayName']=='Tackle']

In [14]:
pass_outcome = mctom_pass['outcomeType.displayName'].value_counts()
pass_total = pass_outcome['Successful'] + pass_outcome['Unsuccessful']

In [15]:
pass_outcome

Successful      413
Unsuccessful     90
Name: outcomeType.displayName, dtype: int64

In [55]:
pass_percentange = (pass_outcome['Successful']/pass_total)*100
pass_percentange

80.91286307053942